### ISSUE TITLE
No Arduino Support

### ISSUE THREAD

**Issue by TeslaLaserRay** [milkv-duo/duo-buildroot-sdk#114]
In any newer version than 1.0.9 is no Support for Arduino, please fix that.

**Comment by mikekgr** [comment]
I came to github to ask the same question : When gentlemen will have the Arduino functionality back ?
Please increase this task priority.

Thanks

**Comment by BoryaGames** [comment]
Yes, please do that, I'm already ordered Duo S, and one of the main reasons I need it - for arduino. I hope you'll do that in month or two while I'll get it.

**Comment by BoryaGames** [comment]
I got it, seems to work, still no arduino :(

**Comment by mikekgr** [comment]
@carbonfix  Please give us an answer when we will have Arduino support updated. Thanks !

**Comment by carbonfix** [comment]
We will update the version next week. If you need it urgently, you can compile it yourself using the arduino branch, the code has been updated :)

**Comment by mikekgr** [comment]
> We will update the version next week. If you need it urgently, you can compile it yourself using the arduino branch, the code has been updated :)

Thanks a lot. I appreciate your work. I think, it's better to wait for you official release.

**Comment by carbonfix** [comment]
> > We will update the version next week. If you need it urgently, you can compile it yourself using the arduino branch, the code has been updated :)
> 
> Thanks a lot. I appreciate your work. I think, it's better to wait for you official release.

Already released in advance:
https://github.com/milkv-duo/duo-buildroot-sdk/releases/tag/Duo-V1.1.2

**Comment by BoryaGames** [comment]
> > > We will update the version next week. If you need it urgently, you can compile it yourself using the arduino branch, the code has been updated :)
> > 
> > 
> > Thanks a lot. I appreciate your work. I think, it's better to wait for you official release.
> 
> Already released in advance: https://github.com/milkv-duo/duo-buildroot-sdk/releases/tag/Duo-V1.1.2

Duo S still doesn't support arduino, any ETA for it, please?
