### ISSUE TITLE
can't enable module compilation in kernel

### ISSUE THREAD

**Issue by khorght** [milkv-duo/duo-buildroot-sdk#159]
Hi. If i use "make menuconfig" in linux_5.10  folder, i see MT7601U net-wireless driver and can enable it as loadable module [M], but it's not included in compilation anyway. If i use menuconfig_kernel, MT7601U disappears and can't be even selected. How can i enable this driver to be compiled as loadable module?

**Comment by khorght** [comment]
Tryed simple "make modules" inside linux_5.10 folder but got error in pgtable.h: KERN_VIRT_START initializer element is not constant. FAIL.
Copyed mt7601u sources from kernel tree, made my own makefile recipe to compile external module, compiled but insmod on milkv crashes whole os with Out of Memory. FAIL.

**Comment by wojtess** [comment]
Did you solve problem?
