### ISSUE TITLE
拉取代码失败

### ISSUE THREAD

**Issue by LittleJober** [milkv-duo/duo-buildroot-sdk#22]
Checking connectivity: 127057, done.
error: invalid path 'buildroot-2021.05/dl/musl-compat-headers/queue.h?rev=1.70'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'

**Comment by LittleJober** [comment]
不过, 我是在windows下拉取的代码，但是在linux下没有问题

**Comment by carbonfix** [comment]
不能在Windows下NTFS格式的文件系统上存放linux下的文件，一些文件名或者一些linux下特有的文件属性与Windows不兼容
