### ISSUE TITLE
Random MAC Address on every boot

### ISSUE THREAD

**Issue by scholt** [milkv-duo/duo-buildroot-sdk#33]
Hello there,

I use a milkV Duo with an attached Ethernet Port. Unfortunately every time I boot the device it get's a new random MAC Address. 

How can this be avoided?

**Comment by carbonfix** [comment]
You can try this:
```
echo "pre-up ifconfig eth0 hw ether 78:01:B3:FC:E8:55" >> /etc/network/interfaces
```
then reboot the board.

https://github.com/milkv-duo/duo-buildroot-sdk#using-the-io-board-baseboard
