### ISSUE TITLE
如何使Linux使用2个内核？

### ISSUE THREAD

**Issue by AliveGh0st** [milkv-duo/duo-buildroot-sdk#34]
我看到cv1800b不支持SMP，只支持AMP，所以无论如何一个任务也无法同时使用两个内核吗？而且大核貌似被锁了850Mhz？有办法解决么

**Comment by coinight** [comment]
群里有补丁，开1ghz

**Comment by carbonfix** [comment]
大核1G运行还不稳定，不建议开。

**Comment by carbonfix** [comment]
大小核可以互相通讯，但同一个任务是不能同时使用两个核的，各自跑各自的应用。
