### ISSUE TITLE
Please use make savedefconfig to create the _defconfig file instead of copying .config.

### ISSUE THREAD

**Issue by chemwolf6922** [milkv-duo/duo-buildroot-sdk#38]
Please refer to https://buildroot.org/downloads/manual/manual.html 9.3.
Using a proper defconfig file will make it easier to spot what differences are made. And potentially make it easier to update to newer buildroot versions.

**Comment by LevitatingBusinessMan** [comment]
I have run into this issue as well. 

The `spinand` / `spinor` configs _are_ properly saved, you can easily tell the difference:
```
wc -l configs/milkv-duo256m_musl_riscv64_defconfig configs/milkv-duo256m-spinand_musl_riscv64_defconfig
  556 configs/milkv-duo256m_musl_riscv64_defconfig
   46 configs/milkv-duo256m-spinand_musl_riscv64_defconfig
  602 total
```

See https://buildroot.org/downloads/manual/manual.html#customize-store-buildroot-config

@carbonfix If a PR was made to properly save the config files, would it be accepted?
