### ISSUE TITLE
After change linux menuconfig build error

### ISSUE THREAD

**Issue by coinight** [milkv-duo/duo-buildroot-sdk#4]
/home/kilo/Downloads/duo-buildroot-sdk/linux_5.10/drivers/usb/dwc2/hcd_intr.c: In function 'dwc2_hc_chhltd_intr_dma':
/home/kilo/Downloads/duo-buildroot-sdk/linux_5.10/drivers/usb/dwc2/hcd_intr.c:1988:4: error: expected '}' before 'else'
 1988 |  } else {
      |    ^~~~

**Comment by carbonfix** [comment]
Try using the latest code. If the compilation still fails, it is recommended that you use Docker to compile:
https://github.com/milkv-duo/duo-buildroot-sdk#2-compiled-using-docker
