### ISSUE TITLE
我如何运行别的risc-v操作系统

### ISSUE THREAD

**Issue by summer-boythink** [milkv-duo/duo-buildroot-sdk#42]
https://github.com/rcore-os/rCore-Tutorial-v3

我想要在duo上运行这个操作系统，该怎么做？
如果你知道，请告诉我，感谢！

**Comment by carbonfix** [comment]
可以先参考一下这个帖子:
https://community.milkv.io/t/uboot/181/4

**Comment by summer-boythink** [comment]
> 可以先参考一下这个帖子: https://community.milkv.io/t/uboot/181/4

感谢！
