### ISSUE TITLE
How to make change to config of buildroot?

### ISSUE THREAD

**Issue by sidianneng** [milkv-duo/duo-buildroot-sdk#6]
I am trying to add dtc to my target image of milk-duo.
When I want to change the config of kernel, I can run `menuconfig_kernel`. But I can't find a way to change the config of buildroot.
Is there any way I can achieve this?

Looking forward to your reply~

**Comment by sidianneng** [comment]
Add the config you want to buildroot-2021.05/configs/milkv_duo_musl_riscv64_defconfig. And it works fine .

**Comment by wojtess** [comment]
How did you resolve issue? Did you manage to config which packages you want to include in image?
