### ISSUE TITLE
How to change the root partition size of Duo 256M?

### ISSUE THREAD

**Issue by shiptux** [milkv-duo/duo-buildroot-sdk#69]

**Comment by thiagohdaqw** [comment]
The easiest way I found was to put it on the PC and resize it with gparted

**Comment by shiptux** [comment]
> The easiest way I found was to put it on the PC and resize it with gparted

Yeah. I use fdisk to resize the rootfs. But I can also use "milkv/genimage-milkv-duo.cfg" file to change the default size of the root partition in the last version. This file seems be deleted.

**Comment by carbonfix** [comment]
Duo:            device/milkv-duo/genimage.cfg
Duo256M:   device/milkv-duo256m/genimage.cfg
DuoS:          device/milkv-duos-sd/genimage.cfg

**Comment by shiptux** [comment]
> The easiest way I found was to put it on the PC and resize it with gparted



> Duo: device/milkv-duo/genimage.cfg Duo256M: device/milkv-duo256m/genimage.cfg DuoS: device/milkv-duos-sd/genimage.cfg

Thank you very much.
