### ISSUE TITLE
使用 menuconfig 添加 python rootfs package 不生效

### ISSUE THREAD

**Issue by weilinfox** [milkv-duo/duo-buildroot-sdk#7]
## 环境信息

+ OS: Ubuntu 20.04 LTS x86_64
+ sdk: 主线最新

### 添加选项

```bash
export PATH=/usr/sbin/:$PATH

export MILKV_BOARD=milkv-duo
source milkv/boardconfig-milkv-duo.sh
source build/milkvsetup.sh
defconfig cv1800b_milkv_duo_sd
menuconfig
```

![menuconfig](https://github.com/milkv-duo/duo-buildroot-sdk/assets/54651938/74f21274-47cc-4bd0-aafc-c8e20d26fd2e)

![diff_config](https://github.com/milkv-duo/duo-buildroot-sdk/assets/54651938/7db52c76-3701-4cc3-964b-6893faaa1a51)

或直接添加

```bash
vim build/boards/cv180x/cv1800b_milkv_duo_sd/linux/cvitek_cv1800b_milkv_duo_sd_defconfig

# 在最后添加
CONFIG_TARGET_PACKAGE_PYTHON3.7=y
```

### 构建

```bash
clean_all
build_all
pack_sd_image
```

或者一键编译

```bash
./build_milkv.sh
```

## 复现结果

构建过程中没有构建 python ，生成的镜像中也不包含 python

**Comment by sidianneng** [comment]
我猜测官方SDK中的python相关的配置最后都是通过buildroot来进行实现的，你可以尝试直接修改buildroot中的相关配置项看看

**Comment by carbonfix** [comment]
最新SDK中已加入python相关配置，具体可参考该提交: https://github.com/milkv-duo/duo-buildroot-sdk/commit/7b7afd9727aed50f0e025099731eb8325b5744ee
