### ISSUE TITLE
如何编译既支持LVGL又支持arduino的镜像？

### ISSUE THREAD

**Issue by xpww** [milkv-duo/duo-buildroot-sdk#79]
在官方例程中，支持lvgl需要打补丁后重新编译镜像，可是这样就会覆盖掉在官网releases提供的编译好了的arduino-duo-image，我怎么能让镜像都支持二者呢？

**Comment by carbonfix** [comment]
arduino 有单独的分支：[arduino](https://github.com/milkv-duo/duo-buildroot-sdk/tree/arduino)

可以尝试在这个分支上打 lvgl 的补丁
