### ISSUE TITLE
USB Audio Driver Error

### ISSUE THREAD

**Issue by devemin** [milkv-duo/duo-buildroot-sdk#85]
Hello!

Milk-V Duo 256MB
I build kernel, But RNDIS driver is not working. alternatively USB Audio (source & sink )appeared.

Is this commit wrong update ???

https://github.com/milkv-duo/duo-buildroot-sdk/commit/2af594800dfd9628a037351986e969e3b049aa39

Thanks.

![image](https://github.com/milkv-duo/duo-buildroot-sdk/assets/52738228/1b4ab2be-87c3-40be-85dc-5f2ece037356)

![image](https://github.com/milkv-duo/duo-buildroot-sdk/assets/52738228/32c9d336-f36c-4298-8d77-a5606bc7dff1)

![image](https://github.com/milkv-duo/duo-buildroot-sdk/assets/52738228/f22dd39d-f879-4311-a475-eca241063fe6)

**Comment by carbonfix** [comment]
fixed:
https://github.com/milkv-duo/duo-buildroot-sdk/commit/bee2e35944e38da76326911ed1913823ca8d4164

**Comment by devemin** [comment]
Thanks,

But the today recent repository can't use RNDIS.

**Comment by devemin** [comment]
(pre-build official image can use RNDIS.)

https://milkv.io/ja/docs/duo/getting-started/boot

**Comment by carbonfix** [comment]
The RNDIS problem is caused by this USB Audio problem, so use the latest code and it will be normal.

**Comment by devemin** [comment]
OK!

I will download again and try it!
Thank you~~~~😊
